version: '3'

services:
    meeting_room_backend_dev:
        image: meeting_room_backend_dev
        ports:
            - "5000:5000"
        restart: always
        volumes:
            - ./:/code
        networks:
            - code-network-dev
networks:
    code-network-dev:
        driver: bridge
